version: "3.4"
services:
  
  

  nginx:
    
    image: yeeecheng/crontab-nginx
    container_name: nginx-server
    restart: on-failure:5
    ports:
      - "8888:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - /etc/localtime:/etc/localtime
  linux_server:
      
   
                       
    image: sunny1928/smart_farm

    depends_on:
      - linux_sql
    restart: on-failure


  linux_sql:
    image: mysql
    environment:
      - MYSQL_DATABASE=smart_farm_db 
      - MYSQL_ROOT_PASSWORD=a10955




