version: "3.4"
services:
  
  

  nginx:
    
    image: crontab-nginx
    container_name: nginx-server
    restart: always
    ports:
      - "8888:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
